In [1]:
import torch

In [5]:
x = torch.randn(2, 3) # two rows, three columns
x

tensor([[ 1.8293,  1.0069,  0.5743],
        [-0.8632, -0.5266,  0.3418]])

In [7]:
x_0 = torch.stack((x, x), dim=0)
print(x_0, x_0.shape)

tensor([[[ 1.8293,  1.0069,  0.5743],
         [-0.8632, -0.5266,  0.3418]],

        [[ 1.8293,  1.0069,  0.5743],
         [-0.8632, -0.5266,  0.3418]]]) torch.Size([2, 2, 3])


In [8]:
x_1 = torch.stack((x, x), dim=1)
print(x_1, x_1.shape)

tensor([[[ 1.8293,  1.0069,  0.5743],
         [ 1.8293,  1.0069,  0.5743]],

        [[-0.8632, -0.5266,  0.3418],
         [-0.8632, -0.5266,  0.3418]]]) torch.Size([2, 2, 3])


In [9]:
torch.cat((x,x), dim=1)

tensor([[ 1.8293,  1.0069,  0.5743,  1.8293,  1.0069,  0.5743],
        [-0.8632, -0.5266,  0.3418, -0.8632, -0.5266,  0.3418]])